---
- name: Deploy to Tomcat
  host: web
  become: yes
  tasks:
  - name: Copy WAR file to Tomcat
    copy:
     src: "/var/snap/jenkins/4865/workspace/MavenAnsible-CICD/target/MavenWebAppJenkinsIntegrationusingAnsible.war"
     dest: "/opt/tomcat/webapps/MavenAnsibleWebApp.war"
     remote_src: no
   
  - name: Restart Tomcat
  systemd:
  name: tomcat
  state: restarted
